apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pgs3cr3t
  POSTGRES_DB: postgres
  DATABASE_URI: postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/postgres